### ISSUE TITLE
Video Download TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 5trubel** [ihabunek/twitch-dl#103]
Python Version: 
Python 3.10.4

Twitch-DL Version: 
1.22.0

Stacktrace:
```
Fetching access token...
Fetching playlists...
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/twitchdl/console.py", line 279, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/twitchdl/commands/download.py", line 167, in download
    return _download_video(video_id, args)
  File "/usr/local/lib/python3.10/dist-packages/twitchdl/commands/download.py", line 280, in _download_video
    playlists_m3u8 = twitch.get_playlists(video_id, access_token)
  File "/usr/local/lib/python3.10/dist-packages/twitchdl/twitch.py", line 355, in get_playlists
    "nauth": access_token['value'],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ihabunek** [comment]
I cannot reproduce this issue. Does it happen every time? Would you mind sharing which video this happens on?

**Comment by 5trubel** [comment]
Ok, now it's working, I think this is just a temporary Problem on Twitchs side
