### ISSUE TITLE
V2 403 Forbidden Error

### ISSUE THREAD

**Issue by sherlockes** [ihabunek/twitch-dl#108]
Since the update to version 2 I am not able to download any videos due to what seems to be an "Error 403". I have Python version 3.8.10 installed. This is the error that appears.

```
sherlockes@imedia:~$ python3 twitch-dl.pyz info 1569618594
Fetching video...
Fetching access token...
Fetching playlists...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "twitch-dl.pyz/__main__.py", line 3, in <module>
  File "twitch-dl.pyz/twitchdl/console.py", line 307, in main
  File "twitch-dl.pyz/twitchdl/commands/info.py", line 21, in info
  File "twitch-dl.pyz/twitchdl/twitch.py", line 360, in get_playlists
  File "twitch-dl.pyz/httpx/_models.py", line 736, in raise_for_status
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://usher.twitch.tv/vod/1569618594?nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Atrue%2C%22reason%22%3A%22UNAUTHORIZED_ENTITLMENTS%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%22160p30%22%2C%22360p30%22%2C%22480p30%22%2C%22720p30%22%2C%22audio_only%22%2C%22chunked%22%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1661874756%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1569618594%7D&nauthsig=f66dfc8b500d85249ebf616b3eeb41ce762ba6e6&allow_audio_only=true&allow_source=true&player=twitchweb'
For more information check: https://httpstatuses.com/403
```

**Comment by ihabunek** [comment]
This is not a problem with version 2, that part of the code did not change. I tried your example with 1.22.0 and I get the same error. 

That video seems to be broken on twitch.tv also: https://www.twitch.tv/videos/1569618594

It does not play and there is an error in the console similar to what you get:

> Player stopping playback - error MasterPlaylist:10 (ErrorAuthorization code 5 - unauthorized_entitlements)

To conclude, this seems to be a twitch.tv problem.
