### ISSUE TITLE
RuntimeError: The connection pool was closed while 5 HTTP requests/responses were still in-flight.

### ISSUE THREAD

**Issue by JC-Chung** [ihabunek/twitch-dl#111]
`twitch-dl download video_id -q audio_only -f m4a` (Just `twitch-dl download video_id` still get same error.)

version: `twitch-dl-2.0.0`
And `twitch-dl-1.22.0` can work.

```
[2mLooking up video...[0m
Found: [94m_______[0m by [93m_______[0m
Output: [94m2022-08-31_1577784963________.m4a[0m
[2mFetching access token...[0m
[2mFetching playlists...[0m
[2mFetching playlist...[0m

Downloading 1172 VODs using 5 workers to E:\Temp\twitch-dl\e8cc359fe7093552769e_1661945941\audio_only
Downloaded 1/1172 VODs [94m0%[0m of [94m~303.1MB[0m at [94m991.7kB/s[0m ETA [94m05:12[0m     Traceback (most recent call last):
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\http.py", line 129, in download_all
    await asyncio.gather(*tasks)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\http.py", line 106, in download_with_retries
    return await download(client, task_id, source, target, progress, token_bucket)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\http.py", line 86, in download
    os.rename(tmp_target, target)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process. : 'E:\\Temp\\twitch-dl\\e8cc359fe7093552769e_1661945941\\audio_only\\00000.ts.tmp' -> 'E:\\Temp\\twitch-dl\\e8cc359fe7093552769e_1661945941\\audio_only\\00000.ts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\Scripts\twitch-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\console.py", line 314, in main
    args.func(args)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\commands\download.py", line 170, in download
    download_one(video_id, args)
  File "C:\Users\test01\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\commands\download.py", line 176, in download_one
    return _download_video(video_id, args)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\commands\download.py", line 313, in _download_video
    asyncio.run(download_all(sources, targets, args.max_workers, rate_limit=args.rate_limit))
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\twitchdl\http.py", line 129, in download_all
    await asyncio.gather(*tasks)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1975, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "C:\Users\_\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 5 HTTP requests/responses were still in-flight.
```

**Comment by nftchance** [comment]
Also experiencing this issue.

It was working correctly and has magically broken with no changes made or anything of the sort. Even force deleting the TEMP registry just re-creates it and then errors.

Uninstalling twitch-dl changes nothing.

**Comment by RobotsOnDrugs** [comment]
I'm getting the exact same error, even with `-w 1`, and with both Python 3.9 and 3.10. No idea what happened, but 2.0.0 did work previously for me as well.

Oddly enough, I tried on my FreeBSD machine, and it had no issues, but this error definitely appears on Windows.

**Comment by ihabunek** [comment]
This should be fixed in 2.0.1. Please test and report back, since I don't have a windows box to check it on. Thanks!

@nftchance Thanks for the pointer, that was the problem. I was renaming the file while it was still open. This worked on linux but broke on windows. The fix is [whitespace only](https://github.com/ihabunek/twitch-dl/commit/c9ab6237e8269a9ffa8ecc0bf350b18a5b82a11d).

**Comment by JC-Chung** [comment]
@ihabunek It is now working properly, thanks!

**Comment by nftchance** [comment]
Excellent, thanks @ihabunek appreciate the rapid fix!
