### ISSUE TITLE
VOD cannot be download - HTTP Status Error: Client error '403 Forbidden'

### ISSUE THREAD

**Issue by sulsoyy** [ihabunek/twitch-dl#113]
Hi!

I am trying to download a twitch VOD but I keep getting error messages like this:

> soyy@Soyeons-MacBook-Pro ~ % twitch-dl download https://www.twitch.tv/videos/1634782454
Looking up video...
Found: 청국장 맛집도전 eating my fav korean food by YuriJoa
Output: 2022-10-26_1634782454_yurijoa_청국장_맛집도전_eating_my_fav_korean_food.mkv
Fetching access token...
Fetching playlists...
Traceback (most recent call last):
  File "/Users/soyy/.local/bin/twitch-dl", line 8, in <module>
    sys.exit(main())
  File "/Users/soyy/.local/pipx/venvs/twitch-dl/lib/python3.10/site-packages/twitchdl/console.py", line 314, in main
    args.func(args)
  File "/Users/soyy/.local/pipx/venvs/twitch-dl/lib/python3.10/site-packages/twitchdl/commands/download.py", line 170, in download
    download_one(video_id, args)
  File "/Users/soyy/.local/pipx/venvs/twitch-dl/lib/python3.10/site-packages/twitchdl/commands/download.py", line 176, in download_one
    return _download_video(video_id, args)
  File "/Users/soyy/.local/pipx/venvs/twitch-dl/lib/python3.10/site-packages/twitchdl/commands/download.py", line 289, in _download_video
    playlists_m3u8 = twitch.get_playlists(video_id, access_token)
  File "/Users/soyy/.local/pipx/venvs/twitch-dl/lib/python3.10/site-packages/twitchdl/twitch.py", line 346, in get_playlists
    response.raise_for_status()
  File "/Users/soyy/.local/pipx/venvs/twitch-dl/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://usher.twitch.tv/vod/1634782454?nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%22160p30%22%2C%22360p30%22%2C%22480p30%22%2C%22720p60%22%2C%22audio_only%22%2C%22chunked%22%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1667115313%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1634782454%7D&nauthsig=90aa6a76de148db3f99e959dfa6c90b3c1d3ae3c&allow_audio_only=true&allow_source=true&player=twitchweb'
For more information check: https://httpstatuses.com/403<

It says 'HTTPStatusError: Client error '403 Forbidden'...

Twitch-dl worked on this channel few days ago but now it's not working. 
I am subscribed to this channel. 

**Link to the VOD:** https://www.twitch.tv/videos/1634782454

**Comment by ihabunek** [comment]
This is a subscriber-only VOD. Perhaps it was made subscriber-only recently and that is why it worked before.

Check out the docs on how to download it:
https://twitch-dl.bezdomni.net/commands/download.html#downloading-subscriber-only-vods
