### ISSUE TITLE
info doesn't work with subscriber-only VODs

### ISSUE THREAD

**Issue by superbonaci** [ihabunek/twitch-dl#128]
Command `twitch-dl info url --auth-token abc` for [subscriber-only VODs](https://twitch-dl.bezdomni.net/commands/download.html#downloading-subscriber-only-vods) does not work, however `twitch-dl download url --auth-token abc` does work.

**Comment by adiosocelote** [comment]
I tried to download a sub-only video today, and I get this traceback, even though I did follow the [link](https://twitch-dl.bezdomni.net/commands/download.html#downloading-subscriber-only-vods):

```Fetching access token...
Fetching playlists...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/bin/twitch-dl/__main__.py", line 3, in <module>
  File "/usr/bin/twitch-dl/twitchdl/console.py", line 321, in main
  File "/usr/bin/twitch-dl/twitchdl/commands/download.py", line 170, in download
  File "/usr/bin/twitch-dl/twitchdl/commands/download.py", line 176, in download_one
  File "/usr/bin/twitch-dl/twitchdl/commands/download.py", line 292, in _download_video
  File "/usr/bin/twitch-dl/twitchdl/twitch.py", line 347, in get_playlists
  File "/usr/bin/twitch-dl/httpx/_models.py", line 749, in raise_for_status
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://usher.ttvnw.net/vod/1976451056?nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%22160p30%22%2C%22360p30%22%2C%22480p30%22%2C%22720p60%22%2C%22audio_only%22%2C%22chunked%22%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1700374436%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3A113628871%2C%22version%22%3A2%2C%22vod_id%22%3A1976451056%7D&nauthsig=5e8b1e8fda6b5b510e3eda418038c89a28cc2c17&allow_audio_only=true&allow_source=true&player=twitchweb'
For more information check: https://httpstatuses.com/403
```

[Screenshot of where I got the auth token from.](https://i.imgur.com/2DEfEOv.png)
Command used: `twitch-dl download https://www.twitch.tv/videos/1976451056 --auth-token k7j6pd`... (I've cut the token on purpose, not quite sure how it works exactly so I did that for safety).

I don't know if this has anything to do with account verification. Twitch requires now (since around February I believe) to give them your phone number in order to use the website to its fullest, and because I value my privacy I did not do it, so my account can only watch streams, videos, receive gifts and chat in channels that I'm mod or VIP in. Can someone verify that sub-only videos can be downloaded? I'd want to know if it's an issue with verification or just Twitch changing something again. 
Thank you in advance.

PS: I decided against making a separate issue because I did not want to clutter the repo with similar issues.

**Comment by superbonaci** [comment]
@adiosocelote `twitch-dl` hasn't been updated in a few months, try with https://github.com/lay295/TwitchDownloader

**Comment by adiosocelote** [comment]
That doesn't seem to work either. Guess it's an account problem or something, unless there was a recent change with Twitch that hasn't been cracked yet.

**Comment by superbonaci** [comment]
report the bug there then
