### ISSUE TITLE
Client error '400 Bad Request' in v2.1.4

### ISSUE THREAD

**Issue by cmdr-xpedros** [ihabunek/twitch-dl#148]
Trying to download video with --auth-token and there is an error (sensitive data censored):

>Fetching access token...
Fetching playlists...
Traceback (most recent call last):
  File "/home/user/.local/bin/twitch-dl", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/console.py", line 321, in main
    args.func(args)
  File "/home/user/.local/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/commands/download.py", line 170, in download
    download_one(video_id, args)
  File "/home/user/.local/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/commands/download.py", line 176, in download_one
    return _download_video(video_id, args)
  File "/home/user/.local/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/commands/download.py", line 292, in _download_video
    playlists_m3u8 = twitch.get_playlists(video_id, access_token)
  File "/home/user/.local/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/twitch.py", line 347, in get_playlists
    response.raise_for_status()
  File "/home/user/.local/pipx/venvs/twitch-dl/lib/python3.8/site-packages/httpx/_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://usher.ttvnw.net/vod/xxxxxxxxxxx?nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1704808187%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Axxxxxxxxx%2C%22version%22%3A2%2C%22vod_id%22%3Axxxxxxxxxx%7D&nauthsig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&allow_audio_only=true&allow_source=true&player=twitchweb'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Comment by ihabunek** [comment]
I'm unable to reproduce this issue, could you run it with extra logging and see if any of the responses contains an error which might tell us what's up?

Add `--debug --verbose` to the command after twitch-dl like this:

```
twitch-dl --debug --verbose download 1234567890 --auth-token 123456789abcdef
```
