### ISSUE TITLE
Error installing twitch-dl via pipx install twitch-dl

### ISSUE THREAD

**Issue by Tiago-classy** [ihabunek/twitch-dl#152]
Hi!
I am trying to install twitch-dl in a docker container via pipx.
Everything runs smoothly, only fails when I try to check the twitch-dl version, that pops up this error:

root@test:/usr/local/bin/twitch-dl --version
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 5, in <module>
    from twitchdl.cli import cli
  File "/opt/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/cli.py", line 9, in <module>
    from twitchdl.entities import DownloadOptions
  File "/opt/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/entities.py", line 6, in <module>
    class DownloadOptions:
  File "/opt/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/entities.py", line 7, in DownloadOptions
    auth_token: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

This method work in the past...

**Comment by ihabunek** [comment]
I broke compat with python < 3.10 by using union types (in this case `str | None`). Fixed in v.2.2.1, please upgrade and test.

**Comment by Tiago-classy** [comment]
New error pops up:
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 5, in <module>
    from twitchdl.cli import cli
  File "/opt/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/cli.py", line 10, in <module>
    from twitchdl.entities import DownloadOptions
  File "/opt/pipx/venvs/twitch-dl/lib/python3.8/site-packages/twitchdl/entities.py", line 25, in <module>
    Data = dict[str, Any]
TypeError: 'type' object is not subscriptable

Do you suggest upgrade the python version?

**Comment by ihabunek** [comment]
Please try v. 2.2.2. thanks!

**Comment by ihabunek** [comment]
Cool, thanks for reporting.
