### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable in v2.3.1

### ISSUE THREAD

**Issue by dokdo2005** [ihabunek/twitch-dl#160]
I tried
`py twitch-dl.2.3.1.pyz clips minnie902 --download --all`
and got this error after some clips finished downloading.

```
Traceback (most recent call last):
  File "C:\Users\dokdo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dokdo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\clips\twitch-dl.2.3.1.pyz\__main__.py", line 3, in <module>
  File "E:\clips\twitch-dl.2.3.1.pyz\click\core.py", line 1157, in __call__
  File "E:\clips\twitch-dl.2.3.1.pyz\click\core.py", line 1078, in main
  File "E:\clips\twitch-dl.2.3.1.pyz\click\core.py", line 1688, in invoke
  File "E:\clips\twitch-dl.2.3.1.pyz\click\core.py", line 1434, in invoke
  File "E:\clips\twitch-dl.2.3.1.pyz\click\core.py", line 783, in invoke
  File "E:\clips\twitch-dl.2.3.1.pyz\twitchdl\cli.py", line 156, in clips
  File "E:\clips\twitch-dl.2.3.1.pyz\twitchdl\commands\clips.py", line 38, in clips
  File "E:\clips\twitch-dl.2.3.1.pyz\twitchdl\commands\clips.py", line 72, in _download_clips
  File "E:\clips\twitch-dl.2.3.1.pyz\twitchdl\commands\clips.py", line 49, in _target_filename
TypeError: 'NoneType' object is not subscriptable
```

Update) I found that this error occurs when the twitch-dl encounters the clip deleted by the Twitch system, not by the streamer.

**Comment by ihabunek** [comment]
Fixed in 2.4.0
