### ISSUE TITLE
twitch-dl deletes unrelated files and sub-directories in same directory as `--cache-dir` (effectively acts as unchecked rm -rf)

### ISSUE THREAD

**Issue by ElWombat01** [ihabunek/twitch-dl#168]
**Environment**

```
twitch-dl 0.0.0
Python 3.13.1 (main, Dec  4 2024, 18:05:56) [GCC 14.2.1 20240910]
Platform: Linux-6.11.9-zen1-1-zen-x86_64-with-glibc2.40
--
ffmpeg path: /usr/bin/ffmpeg
ffmpeg version n7.1 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 14.2.1 (GCC) 20240910
configuration: --prefix=/usr --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan --enable-alsa --enable-bzlib --enable-iconv --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-lzma --enable-sdl2 --enable-xlib --enable-zlib --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-v4l2-m2m --enable-vaapi --enable-vdpau --enable-librist --enable-lto --enable-libsvtav1 --enable-libvmaf --enable-cuda-llvm --disable-cuvid --disable-debug --disable-sndio
libavutil      59. 39.100 / 59. 39.100
libavcodec     61. 19.100 / 61. 19.100
libavformat    61.  7.100 / 61.  7.100
libavdevice    61.  3.100 / 61.  3.100
libavfilter    10.  4.100 / 10.  4.100
libswscale      8.  3.100 /  8.  3.100
libswresample   5.  3.100 /  5.  3.100
libpostproc    58.  3.100 / 58.  3.100
```

**Describe the bug**

When using `--cache-dir` on a directory with files unrelated to a Twitch video, when the temp files are cleared up, it deletes the entire directory, files and sub-directories specified with `--cache-dir` regardless of if they are related to twitch-dl or not. 

**To Reproduce**

set `--cache-dir` to `.` in a directory filed with other files/sub-directories and download and merge a Twitch video.

A pretty silly error from me (accidentally deleted my Downloads folder but luckily nothing that important in it) but I do think it is still a good idea to change how this system works (possibly check if files already exist in the directory or use the filenames listed in `playlist.m3u8` and delete those only). Like I say in the title, it has **effectively acted as an `rm -rf`** which imo seems extremely dangerous.

**Comment by ihabunek** [comment]
Well this is terrible. Thanks for reporting. 

I have changed the logic so it only deletes the files and folders which are created by twitch-dl.

The fix is released in 2.9.3. Please test.

**Comment by ElWombat01** [comment]
Seems to be fixed (thank you for that) but I suspect the fix has broken the ability to resume cancelled downloads (for me at least):

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/bin/twitch-dl/__main__.py", line 3, in <module>
    cli()
    ~~~^^
  File "/usr/bin/twitch-dl/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/bin/twitch-dl/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/usr/bin/twitch-dl/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/bin/twitch-dl/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/twitch-dl/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/usr/bin/twitch-dl/twitchdl/cli.py", line 353, in download
    download(list(ids), options)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/twitch-dl/twitchdl/commands/download.py", line 40, in download
    download_one(video_id, args)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/bin/twitch-dl/twitchdl/commands/download.py", line 49, in download_one
    _download_video(video, args)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/bin/twitch-dl/twitchdl/commands/download.py", line 265, in _download_video
    cache = Cache(cache_dir)
  File "/usr/bin/twitch-dl/twitchdl/cache.py", line 79, in __init__
    self.mkdir(root)
    ~~~~~~~~~~^^^^^^
  File "/usr/bin/twitch-dl/twitchdl/cache.py", line 89, in mkdir
    os.mkdir(path)
    ~~~~~~~~^^^^^^
FileExistsError: [Errno 17] File exists: '/tmp/twitch-dl/test'
```
