### ISSUE TITLE
twitch-dl videos command isn't working

### ISSUE THREAD

**Issue by H-F-T** [ihabunek/twitch-dl#17]
The command videos stopped working giving this response:

`F:\>twitch-dl videos Lirik
Traceback (most recent call last):
  File "c:\users\stati\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\stati\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\stati\AppData\Local\Programs\Python\Python36\Scripts\twitch-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\twitchdl\console.py", line 148, in main
    args.func(**args.__dict__)
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\twitchdl\commands.py", line 76, in videos
    user = twitch.get_user(channel_name)
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\twitchdl\twitch.py", line 38, in get_user
    "login": login
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\twitchdl\twitch.py", line 19, in authenticated_get
    response.raise_for_status()
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/users?login=Lirik
`

**Comment by ihabunek** [comment]
Can confirm, twitch broke something again. I'll look into it but can't promise when.

**Comment by ihabunek** [comment]
Downloading still works, so you can find videos on twitch.tv and download them using twitch-dl.

**Comment by H-F-T** [comment]
And it started working again. I don't know if you fixed it or Twitch was performing some tests again but thanks for looking into it. Your tool is really helpful, thank you for keeping it up and running.

**Comment by ihabunek** [comment]
I have not :) They probably broke half the tooling in the world and had to roll it back. Closing this for now. Thanks for reporting, please do so again if it happens.
