### ISSUE TITLE
Doesn't recognize unlisted category videos 

### ISSUE THREAD

**Issue by H-F-T** [ihabunek/twitch-dl#21]
I noticed that whenever there is uncategorized video and I look it up the program breaks giving this error: 
`Traceback (most recent call last):
  File "c:\users\stati\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\stati\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\stati\AppData\Local\Programs\Python\Python36\Scripts\twitch-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\twitchdl\console.py", line 168, in main
    args.func(**args.__dict__)
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\twitchdl\commands.py", line 64, in videos
    print_video(video["node"])
  File "c:\users\stati\appdata\local\programs\python\python36\lib\site-packages\twitchdl\output.py", line 54, in print_video
    game = video["game"]["name"]
TypeError: 'NoneType' object is not subscriptable
usage: twitch-dl download [-h] [-w MAX_WORKERS] [-s START] [-e END]
                          [-f FORMAT] [-k] [--debug] [--no-color]
                          video
twitch-dl download: error: the following arguments are required: video`

**Comment by ihabunek** [comment]
Can you give me an exact command which reproduces this?

**Comment by H-F-T** [comment]
it was `twitch-dl videos` and channel name, under that channel there were vods which had no category on them

**Comment by ihabunek** [comment]
Should be fixed in 1.9.0, please upgrade and test.

**Comment by H-F-T** [comment]
Tested everything works now. Thank you!
