### ISSUE TITLE
Error while joining files

### ISSUE THREAD

**Issue by Johk3** [ihabunek/twitch-dl#3]
Everything seems to go fine until the program starts joining the files,
This is the error code:

Traceback (most recent call last):
  File "C:\Users\johkm\AppData\Local\Programs\Python\Python37-32\Scripts\twitch-dl-script.py", line 11, in <module>
    load_entry_point('twitch-dl==0.1.0', 'console_scripts', 'twitch-dl')()
  File "C:\Users\johkm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twitch_dl-0.1.0-py3.7.egg\twitchdl\console.py", line 81, in main
  File "C:\Users\johkm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twitch_dl-0.1.0-py3.7.egg\twitchdl\commands.py", line 138, in download
  File "C:\Users\johkm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twitch_dl-0.1.0-py3.7.egg\twitchdl\commands.py", line 105, in _join_vods
  File "C:\Users\johkm\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\johkm\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\johkm\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by StevensonJoe** [comment]
Also facing this issues.

**Comment by ihabunek** [comment]
You need to have [ffmpeg](https://ffmpeg.org/download.html) installed and in your path. To check, open the terminal and run `ffmpeg`. It should print a bunch of text starting with something like:

```
ffmpeg version 4.0.3-1 Copyright (c) 2000-2018 the FFmpeg developers
```

I'll add this to the README

**Comment by ihabunek** [comment]
Closing due to no feedback, open a new one if you're still running into this issue, please.
