### ISSUE TITLE
Inability to download stream in progress, part 2

### ISSUE THREAD

**Issue by SimplicityGuy** [ihabunek/twitch-dl#34]
With v `1.10.2`:
```python
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/twitchdl/console.py", line 172, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 182, in download
    return _download_video(video_id, args)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 264, in _download_video
    playlists = list(_parse_playlists(playlists_m3u8))
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 82, in _parse_playlists
    resolution = "x".join(str(r) for r in p.stream_info.resolution)
TypeError: 'NoneType' object is not iterable
```

With v `1.9.0`:
```python
Available qualities:
1) 720p50 [1280x720]
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/twitchdl/console.py", line 168, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 171, in download
    return _download_video(video_id, args)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 226, in _download_video
    selected = _select_quality(parsed.playlists)
  File "/usr/local/lib/python3.8/site-packages/twitchdl/commands.py", line 81, in _select_quality
    resolution = "x".join(str(r) for r in p.stream_info.resolution)
TypeError: 'NoneType' object is not iterable
```

**Comment by BluelyTASer** [comment]
If you use another computer, you should be able to download stream in progress! :O
