### ISSUE TITLE
TypeError: join() argument must be str or bytes, not 'PosixPath' `

### ISSUE THREAD

**Issue by Barrow1990** [ihabunek/twitch-dl#71]
When trying to download a video with:

`twitch-dl download -q source 1086636090`

I get the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/twitch-dl", line 8, in <module>
    sys.exit(main())
  File "/home/chris/.local/lib/python3.5/site-packages/twitchdl/console.py", line 238, in main
    args.func(args)
  File "/home/chris/.local/lib/python3.5/site-packages/twitchdl/commands/download.py", line 133, in download
    return _download_video(video_id, args)
  File "/home/chris/.local/lib/python3.5/site-packages/twitchdl/commands/download.py", line 247, in _download_video
    with open(path.join(target_dir, "playlists.m3u8"), "w") as f:
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
`
```

Anyone know how to resolve this?

**Comment by ihabunek** [comment]
It was a compatibility issue with python 3.5, fixed in [1.16.1](https://github.com/ihabunek/twitch-dl/releases/tag/1.16.1)
